"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from '@/components/layout/Sidebar';
import "./globals.css";
import { useAssessmentStore } from '@/store/useAssessmentStore';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "FIRE DOOR SERVICE - AGU",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isSidebarCollapsed } = useAssessmentStore();

  return (
    <html lang="en">
      <body className="bg-gray-50 text-slate-900">
        <Sidebar />
        <main 
          className={`min-h-screen transition-all duration-300 
            ${isSidebarCollapsed ? 'pl-16' : 'pl-64'}`}
        >
          {children}
        </main>
      </body>
    </html>
  );
}